In [ ]:
import cv2
import numpy as np
import face_recognition as face_rec
import os
from datetime import datetime
def resize(img,size):
    width=int(img.shape[1]*size)
    height=int(img.shape[0]*size)
    dimension=(width,height)
    return cv2.resize(img,dimension,interpolation=cv2.INTER_AREA)

path='student_images'
studentimg=[]
studentName=[]
myList=os.listdir(path)
#print(myList)
for cl in myList:
    curImg=cv2.imread(f'{path}/{cl}') #student_images/Harika.jpg
    studentimg.append(curImg)
    studentName.append(os.path.splitext(cl)[0]) #removes .jpg and stores only Harika
#print(studentName)

def findEncoding(images):
    encoding_list=[]
    for img in images:
        img=resize(img,0.50)
        img=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encodeimg=face_rec.face_encodings(img)[0]
        encoding_list.append(encodeimg)
    return encoding_list

def Mark(name):
    with open('noting.csv','r+') as f:
        myDataList=f.readlines()
        nameList=[]
        for line in myDataList:
            entry=line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now=datetime.now()
            timestr=now.strftime('%H:%M')
            f.writelines(f'\n{name},{timestr}')
                     

encode_list=findEncoding(studentimg)

vid=cv2.VideoCapture(0)

while True:
    success,frame=vid.read()
    smaller_frames=cv2.resize(frame, (0,0) ,None,0.25,0.25)
    smaller_frames=cv2.cvtColor(smaller_frames,cv2.COLOR_BGR2RGB)

    faces_in_frame=face_rec.face_locations(smaller_frames)
    encode_in_frame=face_rec.face_encodings(smaller_frames, faces_in_frame)

    for encodeFace,faceloc in zip(encode_in_frame,faces_in_frame):
        matches=face_rec.compare_faces(encode_list,encodeFace)
        facedis=face_rec.face_distance(encode_list,encodeFace)
        print(facedis)
        matchIndex=np.argmin(facedis)

        if matches[matchIndex]:
            name=studentName[matchIndex].upper()
            y1,x2,y2,x1=faceloc
            y1,x2,y2,x1= y1*4,x2*4,y2*4,x1*4 
            cv2.rectangle(frame,(x1,y1),(x2,y2),(0,255,0),3)
            cv2.rectangle(frame,(x1,y2-25),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(frame, name, (x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX, 1, (255,255,255), 2)
            Mark(name)
    cv2.imshow('video',frame)
    cv2.waitKey(1)   
    

[0.53231268 0.62585454 0.65250264]
[0.40602855 0.56463362 0.63075006]
[0.40464859 0.58092175 0.64331875]
[0.44505891 0.58382632 0.635769  ]
[0.48098469 0.62095983 0.69700529]
[0.44265791 0.5898407  0.6506076 ]
[0.41830424 0.59563347 0.64524879]
[0.41733589 0.58314015 0.63589194]
[0.44561667 0.58222033 0.61378485]
[0.42196437 0.63619132 0.6720636 ]
[0.48182325 0.60880938 0.67753172]
[0.37735029 0.57389359 0.63246803]
[0.44478823 0.62099727 0.66206175]
[0.755655   0.68275898 0.74488138]
[0.68314406 0.33973233 0.61648535]
[0.6467245  0.36499368 0.63868384]
[0.63490477 0.38155976 0.60220846]
[0.65287689 0.31310897 0.62004505]
[0.65243855 0.38641088 0.59669115]
[0.62890114 0.34490742 0.6271554 ]
[0.65175294 0.31161808 0.54909932]
[0.59319135 0.33583624 0.60116967]
[0.64610199 0.37835297 0.63878622]
[0.66074603 0.35680929 0.61389209]
[0.64953215 0.34415881 0.60614262]
[0.64969675 0.36293041 0.61178649]
[0.64390382 0.33671297 0.5946554 ]
[0.62312247 0.32136931 0.59968854]
[0.64287405 0.381327